services:
  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_DB: edp
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080